# Generated by Django 4.2 on 2023-04-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
